# set default profile to 'dev'
spring.profiles.active: test
# ===============================
# = DATA SOURCE
# ===============================
---
spring:
    profiles: development
datasource:
    db-app-stu:
        jdbc-url: jdbc:oracle:thin:@172.28.2.71:1521:orcl
        username: PDT_APP_SV
        password: EbGaX6t6t91gX6t91c9MoS1kKLBZ78
        driver-class-name: oracle.jdbc.OracleDriver
        test-on-borrow: false
        validation-query: SELECT 1 FROM dual
    db-pdt-nhapdiem:
        jdbc-url: jdbc:mysql://172.28.2.32:3306/pdt_nhapdiem?serverTimezone=UTC&autoReconnect=true&useSSL=false
        username: pdtndiem_user_01
        password: xEpFfYfFN2zVoNOe
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: false
        validation-query: SELECT 1 FROM dual
    db-pdt-wss:
        jdbc-url: jdbc:oracle:thin:@172.28.2.71:1521:orcl
        username: DB_WSS
        password: HSGakKL6t991c9b1c9MoS1kKLk691
        driver-class-name: oracle.jdbc.OracleDriver
        test-on-borrow: false
        validation-query: SELECT 1 FROM dual
    db-applocal:
        jdbc-url: jdbc:mysql://localhost:3306/stuapps?serverTimezone=UTC&autoReconnect=true&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: false
        validation-query: SELECT 1 FROM dual
---
spring:
    profiles: test
    datasource:
        db-extra-courses:
            jdbc-url: jdbc:mysql://172.28.2.227:3306/bk_course_test?serverTimezone=UTC&autoReconnect=true&useSSL=false
            username: bkcourse_user01_test
            password: g]9(J{J/k!kZS2)R
            driver-class-name: com.mysql.cj.jdbc.Driver
            test-on-borrow: false
            validation-query: SELECT 1 FROM dual
    data:
        mongodb:
            host: 172.28.2.226
            port: 27017
            database: bk_img
            username: bkimg_user01
            password: bMpzPcQ3wcjPNBLKne
# ===============================
# JPA / HIBERNATE
# ===============================
---
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.MySQLDialect
            current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
# ===============================
# = SECRET KEY ENCRYPT
# ===============================
---
spring:
    profiles: test
secretkey:
    rsaProperties:
        keyStoreName: default.jks
        alias: hcmut.edu.vn
        passWord: hcmut@123$
    desProperties:
        secretKey: 07SXm0sR
        secretKey2: BwnckdxO
    aesProperties:
        secretKey: G-KaPdRgUkXp2s5v8y/B?E(H+MbQeThV
# ===============================
# = EMAIL
# ===============================
---
spring:
    profiles: test
mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: pdt_bot51@hcmut.edu.vn
    password: pdtb0t12345
    port: 587
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                    enable: true
    protocol: smtp
    test-connection: false